# Generated by Django 4.0.4 on 2022-04-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_email_delete_registered_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='email',
            new_name='RegisteredEmail',
        ),
    ]
